openapi: 3.0.1

info:
  title: mck8s
  description: create, add and/or remove Minecraft Server deployments via an api
  version: 0.0.1
  license:
    name: MIT
    url: https://raw.githubusercontent.com/AbandonTech/mck8s/main/LICENSE


tags:
  - name: Server
    description: Interact with Minecraft Server deployments

paths:
  /servers:
    get:
      summary: Get all servers
      tags:
        - Server
      responses:
        200:
          description: All provided servers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Server'

  /server:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Server'
      summary: Create a new server deployment
      tags:
        - Server
      responses:
        200:
          description: Information about server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        404:
          description: Server not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'

  /server/{server_uuid}:
    parameters:
      - name: server_uuid
        in: path
        required: true
        schema:
          type: string

    get:
      summary: Information about server deployment
      tags:
        - Server
      responses:
        200:
          description: Information about server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        404:
          description: Server not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'

    delete:
      summary: Delete a server deployment
      tags:
        - Server
      responses:
        200:
          description: Confirmation of deletion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        404:
          description: Server not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'

components:
  schemas:
    Server:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
    ErrorDetail:
      type: object
      properties:
        error:
          type: string
        detail:
          type: string

